### ISSUE TITLE
Support activation by .mvn/extensions.xml

### ISSUE THREAD

**Issue by seanf** [rrialq/jsr223-profile-activator-extension#1]
Although deployment via `$M2_HOME/lib/ext/` does work, I wasn't able to activate this extension from `.mvn/extensions.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
  <extension>
    <groupId>com.coutemeier.maven</groupId>
    <artifactId>jsr223-profile-activator-extension</artifactId>
    <version>0.2.0-SNAPSHOT</version>
  </extension>
</extensions>
````

Some info about extensions.xml: http://takari.io/2015/03/19/core-extensions.html

Also, it would be good to log an INFO message at startup confirming that the extension is active.

**Comment by rrialq** [comment]
Thank you for trying this extension.
I will make it compatible with the descriptor for suporting this feature.
Reference: http://takari.io/book/91-maven-classloading.html#maven-core-extensions-classloaders

**Comment by seanf** [comment]
Great, thanks. And thank you for that link, too.

**Comment by rrialq** [comment]
@seanf, hi.
I just done the work, and the changes are in the git.
I've tested it with a very simple project and it works as expected.
Now I will try to publish at Maven Central.

**Comment by seanf** [comment]
Thanks @rrialq the extension says it is active, and I do get an error if I use invalid JavaScript, but I can't actually get any profiles to activate. Profile activation only works if I put the jar into `$M2_HOME/lib/ext/`.

**Comment by seanf** [comment]
I have created some integration tests, including one which fails due to the above problem. See https://github.com/rrialq/jsr223-profile-activator-extension/pull/7.

**Comment by seanf** [comment]
I think I know what's causing the problem, although I'm not entirely sure how it can be fixed.

BTW I think JSR223ProfileActivator.evaluateExpression should only return true if the script evaluates to a Boolean with the value `true`. But that doesn't matter unless we can fix the overall activation problem.

I think the fix (AKA breaking change) for https://issues.apache.org/jira/browse/MNG-4565 in `DefaultProfileSelector` has broken the activation - even though `JSR223ProfileActivator` returns `true`, the default `PropertyProfileActivator` returns `false`, and they are ANDed together.

I suspect we would need to replace `DefaultProfileSelector`. There might be some useful ideas in https://github.com/sviperll/ozymandias/tree/master/maven-profiledep-extension.
